---
openapi: 3.0.0
info:
  title: CMR Autocomplete API
  description: Autocomplete usage
  version: 0.1.0

paths:
  /search/collection/autocomplete:
    get:
      tags:
        - autocomplete
      summary: Autocomplete end-point
      description: Returns a list of autocomplete-suggestions
      parameters:
        - name: q
          in: query
          required: true
          example: ice
          schema:
            type: string
        - name: type
          description: optional comma separated list of types to include
          examples:
            single:
              value: platform
            multi:
              value: 'platform,project,instrument,science_keywords'
          in: query
          required: false
          schema:
            type: string
            enum:
              - platforms
              - instruments
              - projects
              - providers
              - spatial_keywords
      responses:
        '200':
          description: A suggestion response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuggestionResponse'
              example:
                query: ex
                results:
                  - type: platform
                    value: ICECUBE
                    score: 0.341234
                  - type: instrument
                    value: ICE AUGER
                    score: 0.289343

        '400':
          description: Bad query or not term provided

  /search/collection/autocomplete/types:
    get:
      tags:
        - autocomplete
      summary: Return valid facet types to filter with
      description: Returns a list of autocomplete-suggestion valid types available to filter
      responses:
        '200':
          description: List of available types to search for with the main endpoint
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              example: ['platform', 'instrument', 'project', 'provider', 'spatial_keyword']

components:
  schemas:
    SuggestionResponse:
      properties:
        query:
          description: Original term provided
          type: string
        results:
          description: Scored matches for autocomplete, returned in decending score value
          type: array
          items:
            $ref: '#/components/schemas/Suggestion'
    Suggestion:
      properties:
        type:
          description: Type of the search facet
          type: string
          example: 'platform'
        value:
          description: Value of the facet filter
          type: string
          example: 'CUBESAT'
        score:
          description: match score against query
          type: number
          example: 0.425123

